const reviews = [
  {
    id: 1,
    name: "Suzanne D",
    rating: 5,
    date: "13 Dec 2021",
    title: "IKEA Furniture Assembly Task completed on 13 Dec, 2021",
    message: "What can I say? I truly believe we got the BEST tasker out there! Abdul and Z were phenomenal. I literally requested a tasker on Saturday, to complete a big job on Sunday morning at 8am and Abdul responded. He rang us to go over the task and assured us he would be with us at 8am Sunday morning. Abdul turned up with his colleague Z and got on with the job in hand. I tried to offer food and drink, but they had come prepared with their own. Abdul and Z were extremely polite and well-mannered, and kept me informed of the progress throughout, even offering some design ideas and pointing me in the direction of the IKEA planner (which I knew nothing about!). They got on with the task and kept the whole area clean and tidy. They came fully equipped and treated my home so respectfully. I've recently moved into this property and have had a nightmare with trades people so it was a refreshing change to have workers who actually knew what they were doing and who kept the area clean and tidy. The wardrobes they fitted are perfectly and I love them! No way could I have done this myself. Tam so impressed with Abdul's and Z's customer service and skill that I will definitely be using them again and will definitely be recommending them to anyone requiring this service. If you need a tasker, trust me, get Abdul and Z on the job. You won't be disappointed!",
    platform: "TaskRabbit",
  },
  {
    id: 2,
    name: "Sue T",
    rating: 5,
    date: "15 Dec 2021",
    title: "IKEA Furniture Assembly Task completed on 15 Dec, 2021",
    message: "Abdul was absolutely amazing. Contacted me prior to the job, arrived on time. Really pleasant and polite showing excellent standards of work, attention to detail and customer satisfaction. In my opinion he went over and above to ensure I was happy. Great job fabulous to work with and I will definitely be using his skills again! ",
    platform: "TaskRabbit",
  },
  {
    id: 3,
    name: "Jackie G",
    rating: 5,
    date: "16 Dec 2021",
    title: "IKEA Furniture Assembly Task completed on 16 Dec, 2021 ",
    message: "Abdul did a great job and the furniture looks great! Communication before the job was excellent, and he was professional, friendly, polite and very conscientious. Would definitely hire again.",
    platform: "TaskRabbit",
  },
  {
    id: 4,
    name: "Scott R",
    rating: 5,
    date: "18 Dec 2021",
    title: "IKEA Furniture Assembly Task completed on 18 Dec, 2021",
    message: "Abdul was fantastic. Very polite and communicative and did a fantastic job with our furniture. Would book him again.",
    platform: "TaskRabbit",
  },
  {
    id: 5,
    name: "Julie J",
    rating: 5,
    date: "19 Dec 2021",
    title: "IKEA Furniture Assembly Task completed on 18 Dec, 2021",
    message: "Lovely young man. Exceptional work and manners. Even cleaned up after himself !!",
    platform: "TaskRabbit",
  },
  {
    id: 6,
    name: "Wei S",
    rating: 5,
    date: "19 Dec 2021",
    title: "Shelf Mounting 2:00 hours worked on 19 Dec, 2021",
    message: "Abdul is thorough and meticulous, provides helpful suggestions, communicates promptly and openly, and takes care to clean up after work is completed. I am happy to have worked with Abdul, and will definitely look to further engagements when needed. ",
    platform: "TaskRabbit",
  },
  {
    id: 7,
    name: "Katie W",
    rating: 5,
    date: "20 Dec 2021",
    title: "IKEA Furniture Assembly Task completed on 17 Dec, 2021",
    message: "Abdul was polite and friendly. Extremely efficient, I would definitely use his services again.",
    platform: "TaskRabbit",
  },
  {
    id: 8,
    name: "Eva C",
    rating: 5,
    date: "21 Dec 2021",
    title: "IKEA Furniture Assembly Task completed on 20 Dec, 2021",
    message: "Abdul was simply amazing...very professional and conscientious who performed the task above and beyond expectations. Great communication, punctual. Highly recommended. ",
    platform: "TaskRabbit",
  },
  {
    id: 9,
    name: "Simon C",
    rating: 4,
    date: "21 Dec 2021",
    title: "IKEA Furniture Assembly Task completed on 20 Dec, 2021",
    message: "Abdul was very organised and make contact quickly. Great team work for an extremely well put together bedroom furniture set.",
    platform: "TaskRabbit",
  },
  {
    id: 10,
    name: "Rezia A",
    rating: 5,
    date: "23 Dec 2021",
    title: "IKEA Furniture Assembly Task completed on 23 Dec, 2021",
    message: "Abdul is very polite and Well Mannered. Completed Task Efficiently with minimal mess and offered additional help. ",
    platform: "TaskRabbit",
  },
  {
    id: 11,
    name: "Sara N",
    rating: 5,
    date: "26 Dec 2021",
    title: "IKEA Furniture Assembly Task completed on 26 Dec, 2021",
    message: "Abdul was absolutely 5/5*. He was punctual, professional and prepared. He did an exceptional job of putting up a big wardrobe, he made sure he did his work perfectly and that is how it is turned out. Abdul is also extremely polite and made me feel at ease. Will definitely use Abdul again over anyone else I've ever used for DIY ect. His work is exceptional. Thank you so much ",
    platform: "TaskRabbit",
  },
  {
    id: 12,
    name: "Sameera D",
    rating: 5,
    date: "29 Dec 2021",
    title: "IKEA Furniture Assembly Task completed on 29 Dec, 2021",
    message: "Abdul M. is highly commendable in all aspects of his role, from his professionalism, execution of the task, effective communication, respectful mannerism and fastidiousness. If you are looking for an individual who will complete your task to the highest degree, then Abdul M. is the person for the task! This individual is an asset to the Task Rabbit team. Thank you immensely for your help today. ",
    platform: "TaskRabbit",
  },
  {
    id: 13,
    name: "Sameera D",
    rating: 5,
    date: "29 Dec 2021 ",
    title: "IKEA Furniture Assembly Task completed on 29 Dec, 2021",
    message: "Abdul M. is highly commendable in all aspects of his role, from his professionalism, execution of the task, effective communication, respectful mannerism and fastidiousness. If you are looking for an individual who will complete your task to the highest degree, then Abdul M. is the person for the task! This individual is an asset to the Task Rabbit team. Thank you immensely for your help today. ",
    platform: "TaskRabbit",
  },
  {
    id: 14,
    name: "Suzette M",
    rating: 5,
    date: "29 Dec 2021",
    title: "Shelf Mounting 1:00 hour worked on 29 Dec, 2021",
    message: "I was really pleased to have Abdul as my tasker. The job was to mount a cabinet and a large notice board to the wall. Abdul was punctual, competent, conscientious, friendly, polite and tidy, and communication about the task was clear. I'll happily request him for future jobs and have no hesitation in recommending him. ",
    platform: "TaskRabbit",
  },
  {
    id: 15,
    name: "Vincent R",
    rating: 5,
    date: "30 Dec 2021",
    title: "Hang Pictures 2:00 hours worked on 30 Dec, 2021",
    message: "Abdul was very polite and pleasant. A tidy and efficient worker, who cared about his work. I wouldn't hesitate in using him again in the future. ",
    platform: "TaskRabbit",
  },
  {
    id: 16,
    name: "Ansar B",
    rating: 5,
    date: "30 Dec 2021 ",
    title: "IKEA Furniture Assembly Task completed on 30 Dec, 2021 ",
    message: "",
    platform: "TaskRabbit",
  },
  {
    id: 17,
    name: "David A",
    rating: 5,
    date: "31 Dec 2021",
    title: "TV Mounting 1:00 hour worked on 30 Dec, 2021",
    message: "Abdul did a very good job of installing my electric wall heater. He was very meticulous, researching the specifics of the job prior to his visit and taking time to ensure the installation was safe and secure. Abdul is a friendly guy and it was a pleasure to have him in my home. Highly recommended! ",
    platform: "TaskRabbit",
  },
  {
    id: 18,
    name: "Aaron C",
    rating: 5,
    date: "31 Dec 2021",
    title: "IKEA Furniture Assembly Task completed on 30 Dec, 2021",
    message: "Top lad & puts his clients first",
    platform: "TaskRabbit",
  },
  {
    id: 19,
    name: "David L",
    rating: 5,
    date: "1 Jan 2022",
    title: "IKEA Furniture Assembly Task completed on 01 Jan, 2022",
    message: "If I could rate Abdul a 6 I would, would a lovely guy, very talented and clever and did a fantastic job. Would 100% recommend him to anyone looking for a job to be done ",
    platform: "TaskRabbit",
  },
  {
    id: 20,
    name: "Kathy C",
    rating: 5,
    date: "3 Jan 2022",
    title: "IKEA Furniture Assembly Task completed on 03 Jan, 2022",
    message: "Abdul was friendly, punctual and efficient. Took on a big wardrobe and had the job done in super quick time. Would not hesitate to recommend for anyone out there looking. ",
    platform: "TaskRabbit",
  },
  {
    id: 21,
    name: "Kathy C",
    rating: 5,
    date: "3 Jan 2022",
    title: "IKEA Furniture Assembly Task completed on 03 Jan, 2022",
    message: "Abdul was friendly, punctual and efficient. Built a large wardrobe perfectly and quickly. I would not hesitate to recommend. ",
    platform: "TaskRabbit",
  },
  {
    id: 22,
    name: "Lama Z",
    rating: 5,
    date: "13 Jan 2022",
    title: "IKEA Furniture Assembly Task completed on 13 Jan, 2022",
    message: "Great job",
    platform: "TaskRabbit",
  },
  {
    id: 23,
    name: "Alexandra N",
    rating: 5,
    date: "17 Jan 2022",
    title: "IKEA Furniture Assembly Task completed on 16 Jan, 2022",
    message: "Abdul was on time, friendly, efficient and professional. Thank you so much for all your hard work Abdul we love our wardrobes and you did a fantastic job! We will see you again soon. ",
    platform: "TaskRabbit",
  },
  {
    id: 24,
    name: "Louise J",
    rating: 5,
    date: "22 Jan 2022",
    title: "IKEA Furniture Assembly Task completed on 22 Jan, 2022",
    message: "Hardworking and very polite. Excellent results!",
    platform: "TaskRabbit",
  },
  {
    id: 25,
    name: "Santosh M",
    rating: 5,
    date: "3 Feb 2022",
    title: "Shelf Mounting 1:00 hour worked on 03 Feb, 2022",
    message: "Abdul was really polite, informative and efficient. He assisted us with putting up some shelves on the plasterboard walls and provided us with screws when we'd lost ours! Very happy with the service. Would highly recommend and would use again. Thanks! ",
    platform: "TaskRabbit",
  },
  {
    id: 26,
    name: "Sirat A",
    rating: 5,
    date: "19 Feb 2022",
    title: "TV Mounting 1:30 hours worked on 18 Feb, 2022",
    message: "Abdul was amazing and very professional. I'm glad I picked him for the job. He was easy to talk to and was reaLly understanding. I initially picked a flimsy bracket for the tV but he offered advice for a better one and for less money too. I would 100% recommend him to anyone. Thank you so much Abdul for transforming my living room. ",
    platform: "TaskRabbit",
  },
  {
    id: 27,
    name: "Nazma B",
    rating: 5,
    date: "20 Feb 2022",
    title: "TV Mounting 1:45 hours worked on 20 Feb, 2022",
    message: "Brilliant! Lovely gentleman. Very meticulous and leaves everything clean and tidy after completing the job. Highly recommended",
    platform: "TaskRabbit",
  },
  {
    id: 28,
    name: "Lorraine H",
    rating: 5,
    date: "5 Mar 2022",
    title: "IKEA Furniture Assembly Task completed on 05 Mar, 2022",
    message: "Abdul 100% The job was done efficiently, very clean and quick.Very nice friendly manner, polite. Very happy with the result.",
    platform: "TaskRabbit",
  },
  {
    id: 29,
    name: "Geoffrey H",
    rating: 5,
    date: "13 Mar 2022",
    title: "IKEA Furniture Assembly Task completed on 12 Mar, 2022",
    message: "Abdul was a an extremely pleasant person who was well organised and completed the task with efficiently and was extremely tidy while doing the task and all the packing materials was compressed and left downstairs for me to dispose off would recommend him and use him for this type of task again thank you ",
    platform: "TaskRabbit",
  },
  {
    id: 30,
    name: "Jacquelyn P",
    rating: 5,
    date: "13 Mar 2022",
    title: "IKEA Furniture Assembly Task completed on 12 Mar, 2022",
    message: "Excellent service. Lovely guy too",
    platform: "TaskRabbit",
  },
  {
    id: 31,
    name: "Soraia G",
    rating: 5,
    date: "18 Mar 2022",
    title: "TV Mounting 1:45 hours worked on 18 Mar, 2022",
    message: "Abdul is a very professional worker and knows what he's doing, I'm being honest he's 5 stars. very dear, attentive, friendly and easy to communicate. He is always attentive to what he is doing and to the customer's taste. I recommend him 100% ",
    platform: "TaskRabbit",
  },
  {
    id: 32,
    name: "Maryam S",
    rating: 5,
    date: "20 Mar 2022",
    title: "IKEA Furniture Assembly Task completed on 20 Mar, 2022",
    message: "Had such a good experience with abdul! Efficient & excellent work ethic! Would deffo recommend to anyone!",
    platform: "TaskRabbit",
  },
];
